apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: databases.meetup.example.com
spec:
  group: meetup.example.com
  version: v1
  names:
    kind: Database
    plural: databases
    scope: Namespaced
